### ISSUE TITLE
GitHub display ordering

### ISSUE THREAD

**Issue by najaco** [QasimWani/LeetHub#304] opened 2022-07-13 16:48 UTC
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
When the directories are submitted, they would be ordered on GitHub by the string ordering rather than natural ordering. For example, this is the order that we see:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/31194472/178787532-7b989fc5-224b-4bc9-bec5-1c38aef907bb.png">

**Describe the solution you'd like**
Perhaps it could instead be written with prepending 0's, such that it would go:
1. 0001-two-sum
2. 0002-add-two-numbers

etc.

**Describe alternatives you've considered**
If the numbering doesn't matter, then maybe it could be removed overall and a table of number to problem could be created/updated in the README.md

**Additional context**

**Comment by deprov447** [comment] 2022-07-31 15:56
duplicate of #229

**Closed** 2023-01-08 00:46 UTC
