### ISSUE TITLE
Images in some problems not shown properly

### ISSUE THREAD

**Issue by trungnguyencs** [QasimWani/LeetHub#53] opened 2020-12-14 04:31 UTC
There's an error displaying images in some problems. For example, the image in this one wasn't displayed properly:
https://github.com/trungnguyencs/Leetcode/tree/main/range-sum-query-2d-immutable
Link to Leetcode problem: https://leetcode.com/problems/range-sum-query-2d-immutable/

**Comment by QasimWani** [comment] 2020-12-14 15:17
interesting... thanks for bringing it up.
Seems like the path was copied incorrectly. Hmm at first I thought this was an issue with native leetcode image vs external ones, but looking at other submissions in your repo, it seems the formatting is not consistent with images. Some are marked as "https://" while other with relative path like the one u pointed out as "/static/..."
Will get to it later this week.
@arnabsen1729  thoughts? Has this happened to you too?

**Comment by QasimWani** [comment] 2020-12-14 15:59
> I think we need to put a check for all the images.

So if its a relative path, prefix it with https://leetcode.com/"
in the above case, this becomes: https://leetcode.com/static/images/courses/range_sum_query_2d.png
Note that leetcode redirects this https://assets.leetcode.com/static_assets/public/images/courses/range_sum_query_2d.png
so not sure that that would be a problem when generating the readme.




> @QasimWani assign me this issue, I will come up with a fix.

assinged! thanks for taking this 👍🏼

**Comment by arnabsen1729** [comment] 2020-12-14 16:04
<div><img src="https://leetcode.com/static/images/courses/range_sum_query_2d.png" ></img></div>

Tested it here :arrow_up:.  Just prefixing with "https://leetcode.com/" will work.

**Comment by QasimWani** [comment] 2021-02-17 15:55
updates? @arnabsen1729

**Closed** 2021-03-01 01:07 UTC
Labels: bug, good first issue

**Comment by getCurrentThread** [comment] 2022-02-28 08:27
Hello. The problem is pinned, but I wonder if it was solved because the issue was closed.

If it's a problem that hasn't been solved yet, I'd like to fix it simply, so can you tell me the line that parses the line?
