### ISSUE TITLE
Problem markdown committed after the code file

### ISSUE THREAD

**Issue by intelcomAnshul** [QasimWani/LeetHub#146] opened 2021-12-10 07:04 UTC
**Description**
The markdown file sometimes gets committed after the problem solution file

**To Reproduce**
1. Solve a question
2. Click on Submit
3. In the code repository, does not display space and time percentage.

**Expected behavior**
The code repository should display space and time percentage instead of "Prepend discussion post - Leethub"
![Capture](https://user-images.githubusercontent.com/82455862/145531686-c16d8d2a-1924-4f89-9ca2-6c771316c7d4.PNG)

**Comment by QasimWani** [comment] 2021-12-10 14:48
That's a feature, not a bug!
It's because you made a discussion post for that problem and LeetHub added that link in the problem description readMe.

**Comment by tuminzee** [comment] 2021-12-15 14:46
@QasimWani I think you should close this issue.

**Closed** 2021-12-15 23:05 UTC
Labels: bug
