### ISSUE TITLE
Add function to add various solutions (varying in time/space complexity) for a particular question 

### ISSUE THREAD

**Issue by priyum7** [QasimWani/LeetHub#55] opened 2020-12-18 01:08 UTC

**Comment by QasimWani** [comment] 2020-12-18 08:08
what? explain your issue in greater detail!

**Comment by priyum7** [comment] 2020-12-19 03:53
For example, lets say I solve question number 255 (any random question) on leetcode using a naive approach and get a time complexity of O(N^2).  Now this will get added to my leethub repo and if later on i solve the same with a better time complexity say O(N), the solutions does not gets added the repository.
I suggest either you can add different implementations varying in time/space complexity into the question  directory in repository or you may give an option to user for replacing current solution into the repository.

**Comment by QasimWani** [comment] 2020-12-19 05:05
please read other issues before raising one! duplicate of #54. fixed issue #56 .
even though your idea is a bit different, overall it's the same - recommit newer versions of your submissions for a problem. That's already done and implemented. To see this in effect, you have to first reload and resubmit the problem. Note that if you don't change your code in the latest submission, it won't be reflected on github because of the way commit hashes work.

Also, the idea about "functions" for time complexity don't seem useful to me. You can't tell the time complexity programmatically without having some form of timer and approximating it from that, which requires a lot of benchmark. This can be done but would be costly in terms of latency and overall browsing times. LeetHub is very fast (~400ms) and the idea you mentioned could well over take 10sec causing tons of problems.
If you can figure out a way to do it better, submit a PR and I'll review it. 
lmk if u have any other questions. closing for now.
Thanks for using LeetHub

**Closed by QasimWani** 2020-12-19 05:05 UTC
Labels: duplicate
