### ISSUE TITLE
Codes not uploading on GitHub

### ISSUE THREAD

**Issue by sid-abc** [QasimWani/LeetHub#131] opened 2021-09-05 06:34 UTC
I tried leethub for the first time, followed all the procedures but codes aren't getting uploaded on GitHub. My repo got created but on submitting the code on leetcode nothing is getting pushed on GitHub.

**Comment by QasimWani** [comment] 2021-09-05 18:28
did you pass all the test cases on the problem you submitted? LeetHub only pushes correctly solved problems. 
Also, when you hit submit, plz wait 1-3 seconds before closing. Network issues may take time for code to be pushed.

**Comment by sid-abc** [comment] 2021-09-05 18:49
> did you pass all the test cases on the problem you submitted? LeetHub only pushes correctly solved problems.
> Also, when you hit submit, plz wait 1-3 seconds before closing. Network issues may take time for code to be pushed.

i did pass all the test cases and waited as well but it didn't get pushed.
![image](https://user-images.githubusercontent.com/69795417/132138047-b3ffa935-ee04-4808-8058-b7f1983fca69.png)
![image](https://user-images.githubusercontent.com/69795417/132138056-c8ce304c-386d-43dc-baa9-d90e00a0ca89.png)

**Comment by QasimWani** [comment] 2021-09-05 19:34
hmm, what's the link to your repository?
can u edit your code a bit (perhaps add a new line) and resubmit? Also, try looking at console window (Fn + F12 / ctrl + shift + I) if it generates any error messages.
Please add as many details as possible. I can't reproduce your error since it works fine with me (even after creating a new repo).

**Comment by sid-abc** [comment] 2021-09-06 16:46
link to my repo https://github.com/sid-abc/Myleetcode

console ss when i submitted 
![image](https://user-images.githubusercontent.com/69795417/132246122-d843d4a4-b509-41f3-bf8f-0c897c4f66fe.png)

**Comment by sid-abc** [comment] 2021-09-06 16:52
![image](https://user-images.githubusercontent.com/69795417/132246594-a79fb412-26c9-4c1f-a74e-6b2bd8132bf4.png)

**Closed** 2021-09-07 15:18 UTC
Labels: bug

**Comment by QasimWani** [comment] 2021-09-08 00:23
hey did you figure it out? sorry, was busy w/ work

**Comment by Nandan-Jena** [comment] 2023-01-03 04:19
hello @QasimWani I am facing an issue similar to this where none of my code is getting submitted to Git hub even after clearing all the test cases and the console window is also showing the same as shown above

**Comment by yosefkazinik** [comment] 2023-01-20 07:47
Does LeetHub retroactively upload all the problems you've already solved before downloading the extension?

**Comment by imenbkr** [comment] 2023-02-24 22:22
Hello @QasimWani I'm currently having the same problem with my leetcode solutions, are there any updates on the issue ?

**Comment by areeba-fatima-4** [comment] 2023-05-21 08:55
I am having the same issue.

**Comment by OliverHeber** [comment] 2023-06-04 15:59
Same issue.

**Comment by areeba-fatima-4** [comment] 2023-06-05 07:32
It is because of the UI update of leetcode. If you revert to the old one, this would work.

**Comment by Swaru09** [comment] 2023-08-18 01:02
same issue

**Comment by sakshipimpale33** [comment] 2024-11-18 09:26
i've also same issue
